services:
  database:
    container_name: clone-tabnews-database
    image: postgres:16.4-alpine3.19
    environment:
      - POSTGRES_PASSWORD=localpassword
    ports:
      - 5432:5432
    volumes:
      - './pg_data:/var/lib/postgresql/data'