services:
  database:
    container_name: clone-tabnews-database
    image: postgres:16.4-alpine3.19
    env_file:
      - ../.env
    ports:
      - 5432:5432
    # volumes:
    #   - './pg_data:/var/lib/postgresql/data'